# Page settings

baseURL = "https://jrbeverly.me/"
languageCode = "en"
title = "Udacity - jrbeverly"
theme = "hugo-devresume-theme"

[params]
    author = "Jonathan Beverly (jrbeverly)"
    description = "Udacity Certificates and Projects"

    primaryColor = "#02B3E4"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Udacity"
        tagline = "jrbeverly certificates"
        avatar = "profile.png"

       [params.skills]
        enable = true

        [[params.skills.items]]
        details = "Using the SCRUM Framework"
        [[params.skills.items]]
        details = "Security for Hackers and Developers"
        [[params.skills.items]]
        details = "JavaScript Core Language"
        [[params.skills.items]]
        details = "ASP.NET MVC5"
        [[params.skills.items]]
        details = "Building Web Applications with React"
        [[params.skills.items]]
        details = "CSS"
        [[params.skills.items]]
        details = "MySQL"
        [[params.skills.items]]
        details = "Windows PowerShell"
        [[params.skills.items]]
        details = "C#"
        [[params.skills.items]]
        details = "HTML5"
        [[params.skills.items]]
        details = "Angular"
        [[params.skills.items]]
        details = "Docker"
        [[params.skills.items]]
        details = "Android"
        [[params.skills.items]]
        details = "C++"
        [[params.skills.items]]
        details = "Java"

    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."

    [params.experience]
        enable = true

        [[params.experience.entry]]
        title = "Machine Learning Nanodegree"

        [[params.experience.entry.list]]
        title = "Classification of Dogs"
        dates = "Fall 2019"
        company = "Udacity"
        details = "My implementation of the Convolutional Neural Networks (CNN) algorithm for identifying a canine’s breed from an image. Additionally, it supply the resembled dog breed if provided an image of a human."
        url = "https://github.com/jrbeverly/dog-project"
        github = "https://github.com/jrbeverly/dog-project"

        [[params.experience.entry.list]]
        title = "Classification of Dogs"
        dates = "Fall 2019"
        company = "Udacity"
        details = "My implementation of the Convolutional Neural Networks (CNN) algorithm for identifying a canine’s breed from an image. Additionally, it supply the resembled dog breed if provided an image of a human."
        url = "https://github.com/jrbeverly/dog-project"
        github = "https://github.com/jrbeverly/dog-project"

        [[params.experience.entry]]
        title = "React Nanodegree"

        [[params.experience.entry.list]]
        title = "Classification of Dogs"
        dates = "Fall 2019"
        company = "Udacity"
        details = "My implementation of the Convolutional Neural Networks (CNN) algorithm for identifying a canine’s breed from an image. Additionally, it supply the resembled dog breed if provided an image of a human."
        url = "https://github.com/jrbeverly/dog-project"
        github = "https://github.com/jrbeverly/dog-project"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/jrbeverly"
        title = "jrbeverly"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://ca.linkedin.com/in/jrbeverly/"
        title = "jrbeverly"

