name: "jrbeverly.dev"
on:
  push:
    # branches:
    # - master
    paths:
    - srv/jrbeverly.dev/*
    - srv/jrbeverly.dev/*
    - srv/jrbeverly.dev/*
    - srv/jrbeverly.dev/*
    - .github/workflows/jrbeverly.dev.netlify.yml

jobs:
  hugo:
    name: Hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cardboardci/hugo:latest
        with:
          args: "ls srv/jrbeverly.dev"
      - uses: docker://cardboardci/hugo:latest
        with:
          args: "bash cd srv/jrbeverly.dev && hugo -d ${GITHUB_WORKSPACE}/artifacts/jrbeverly.dev"
      # - uses: docker://cardboardci/netlify:latest
      #   with:
      #     args: "netlify deploy --dir public --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_TOKEN }} --prod"
      #     working-directory: /srv/jrbeverly.dev