name: "jrbeverly.me"
on:
  push:
    # branches:
    # - master
    paths:
    - srv/jrbeverly.me/*
    - srv/jrbeverly.me/*/*
    - srv/jrbeverly.me/*/*/*
    - srv/jrbeverly.me/*/*/*/*
    - .github/workflows/jrbeverly.me.netlify.yml

jobs:
  hugo:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://cardboardci/netlify:latest
        if: github.ref == 'refs/heads/master'
        with:
          args: "netlify deploy --dir srv/jrbeverly.me/ --site ${{ secrets.NETLIFY_JRBEVERLY_ME }} --auth ${{ secrets.NETLIFY_TOKEN }} --prod"
